Weather Data Analyzer

1. Data Generation (3D Array)

In [1]:
import numpy as np

# Random temperatures between 15°C and 45°C
# Shape: (Cities, Days, Hours)
np.random.seed(42)
weather_data = np.random.randint(15, 46, (3, 7, 24))

print(f"Data Shape: {weather_data.shape}") # Output: (3, 7, 24)


Data Shape: (3, 7, 24)


2. High-Level Analysis (Nested Mean)

In [2]:
# We calculate mean across Axis 1 (Days) and Axis 2 (Hours)
city_weekly_averages = np.mean(weather_data, axis=(1, 2))

cities = ["Islamabad", "Karachi", "Lahore"]
for i in range(3):
    print(f"{cities[i]} Weekly Average: {city_weekly_averages[i]:.2f}°C")


Islamabad Weekly Average: 30.63°C
Karachi Weekly Average: 30.19°C
Lahore Weekly Average: 29.86°C


3. Finding Extremes (The "Hottest Hour")

In [3]:
# Boolean indexing
heatwave_mask = weather_data > 40
heatwave_counts = np.sum(heatwave_mask, axis=2) # Count per city, per day

print("Heatwave hours per city per day:")
print(heatwave_counts)


Heatwave hours per city per day:
[[ 2 10  2  4  6  5  3]
 [ 3  6  8  5  4  3  7]
 [ 4  3  3  2  7  8  4]]
